backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

  # This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "public/images/uploads" # Media files will be stored in the repo under public/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  # to add images in gallery
  - name: "image" # Used in routes, e.g., /admin/collections/blog
    label: "image" # Used in the UI
    folder: "markdown/images" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "image" }
      - { label: "Titre", name: "title", required: true, widget: "string" }
      - label: "Catégorie"
        name: "category"
        required: true
        widget: "select"
        options:
          - { label: "Mariage", value: "mariage" }
          - { label: "Grossesse", value: "grossesse" }
          - { label: "Bébé", value: "bebe" }
          - { label: "Famille", value: "famille" }
          - { label: "Baptême", value: "bapteme" }
          - { label: "Couple", value: "couple" }
      - { label: "Image", name: "thumbnail", required: true, widget: "image" }
      - { label: "Date publication", name: "date", widget: "datetime" }

  # to add prestation description with price
  - name: "prestation" # Used in routes
    label: "prestation" # Used in the UI
    folder: "markdown/prestations" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "prestation",
        }
      - { label: "Titre", name: "title", required: true, widget: "string" }
      - { label: "Date publication", name: "date", widget: "datetime" }
      - { label: "Image", required: true, name: "thumbnail", widget: "image" }
      - {
          label: "Description",
          name: "description",
          required: true,
          widget: "string",
        }
      - { label: "Prix", name: "price", widget: "number", required: false }
      - {
          label: "Prix complément",
          name: "pricecplt",
          widget: "string",
          required: false,
        }
      - { label: "Message", name: "body", widget: "markdown" }
